### ISSUE TITLE
[bug] Smart Mode doesn't detect new files in `_apps`

### ISSUE THREAD

**Issue by Zebradil** [mykso/myks#112]
(I need to double-check that)

To reproduce:
- create file `envs/mykso/dev/_apps/httpbingo/helm/httpbingo.yaml`
- run `myks render`

Result: `Smart Mode did not find any changes. Exiting.`

**Comment by fritzduchardt** [comment]
Isn't this the same issue as #104? Both should be fixed with #113

**Comment by Zebradil** [comment]
Hmm, I can't reproduce it anymore. Closing for now.
