### ISSUE TITLE
Post rendering binary execution

### ISSUE THREAD

**Issue by fritzduchardt** [mykso/myks#135]
We could benefit from a plugable mechanism that allows us to run binaries like [kubeconform](https://github.com/yannh/kubeconform) for each manifest after rendering.

**Comment by Zebradil** [comment]
Hey @fritzduchardt, is this working as expected now? If yes, could you provide an example of how you use kubeconform?

**Comment by fritzduchardt** [comment]
> Hey @fritzduchardt, is this working as expected now? If yes, could you provide an example of how you use kubeconform?

Yes, it is all working reasonably well for me. I guess, we opened a bit of a back door to work around myks, but the plugin approach is definitely better than reinventing the wheel.

**Comment by fritzduchardt** [comment]
resolved by #148
