### ISSUE TITLE
[feat] Local apply

### ISSUE THREAD

**Issue by fritzduchardt** [mykso/myks#138]
Myks is useful even if used only for local chart rendering and validation without actually using a tool like ArgoCD for deployment. Therefore, we could add a mechanism that allows to apply to the local K8s context, e.g. `myks apply envs/env1 app1`

Such a mechanism would also be useful during development as an alternative to deploying from feature-branches.

**Comment by Zebradil** [comment]
Why is a dedicated command is better than using `kubectl apply` or `kapp deploy`?

**Comment by fritzduchardt** [comment]
resolved by #148
