### ISSUE TITLE
[bug] sync on fresh applications no longer works

### ISSUE THREAD

**Issue by fritzduchardt** [mykso/myks#170]
Syncing a fresh application fails on a non-existing "vendor" folder error message.

**Comment by Zebradil** [comment]
This is a duplicate of #157, that is fixed in #159. Or is it still not working?

**Comment by fritzduchardt** [comment]
Thought, I am the only one working over Christmas. Shame on me.

**Comment by fritzduchardt** [comment]
Duplicate
