### ISSUE TITLE
[feat] move helm dependency build to sync command

### ISSUE THREAD

**Issue by fritzduchardt** [mykso/myks#196]
I am wondering, whether the logic for the new helm dependency management should move to the sync phase. I

It only requires re-execution after the user has synced and effectively both "helm repo add" as well as "helm dependency build" can be perceived as syncing your local state with remote state. Plus, the render step is currently slowed down unnecessarily.

@Zebradil and @kbudde, what do you think?

**Comment by kbudde** [comment]
Makes sense. Usually I expect sync to rely on the network, while render should work locally.

Why should it not be part of the sync step?

**Comment by Zebradil** [comment]
Argee. In perspective, we can have `sync`/`prepare` and `render` stages for plugins.

**Comment by fritzduchardt** [comment]
Thank you every so much for your feedback. Then I will get on with it. Thinking of introducing something similar to the `YamlTemplatingTool` interface that we have for the render stage for the sync stage.

**Comment by Zebradil** [comment]
Implemented in #202
