### ISSUE TITLE
[CI] Release announcements to slack

### ISSUE THREAD

**Issue by kbudde** [mykso/myks#203]
We should announce new releases to our shiny new slack channel [#myks](https://kubernetes.slack.com/archives/C06BVDBHZC2)

**Comment by Zebradil** [comment]
I did a quick research on this topic right after we got the channel. GH actions can do that, but to use them we need to request an app or webhook. We can ask in #slack-admins, but it seems like such automations are discouraged (https://github.com/kubernetes/community/blob/master/communication/slack-guidelines.md#requesting-a-bot-token-or-webhook).

But maybe there is another way or admins will allow us to do that. I saw on some other channels there that people post news about releases manually.

**Comment by kbudde** [comment]
Let's close this issue
