### ISSUE TITLE
provide nix packages

### ISSUE THREAD

**Issue by kbudde** [mykso/myks#285]
Nix(os) is nice, let's provide myks for nix users as well.

Initial PR: https://github.com/NixOS/nixpkgs/pull/310785

Needs as well an update to myks (docs), e.g. 

how to run:
```bash
nix-shell -p myks helm git
```

**Comment by Zebradil** [comment]
It's a good idea.

I'm not familiar (anymore) with nix, so I have questions:

- How the version is supposed to be updated there?
- Can we use this feature of GoReleaser: https://goreleaser.com/customization/nix/ ?

**Comment by kbudde** [comment]
Hi, 

Updates will happen automatically. There is a job running and updating the version and hashes automatically following GitHub releases. We just have to ensure that the build process is working.

I had a look at the goreleaser feature before. Unfortunately a nix user repo is not the same as being in the main channel. 

I think the integration into the normal repo will happen soon. 

BR Kris

**Comment by Zebradil** [comment]
> Updates will happen automatically

That is all I need then :-)

**Comment by Zebradil** [comment]
@kbudde https://github.com/NixOS/nixpkgs/pull/310785 is merged 🥳

Could you provide a documentation snippet? Or is this literally all what nix users need?

```shell
nix-shell -p myks helm git
```

**Comment by Zebradil** [comment]
Fixed in NixOS/nixpkgs#310785 and #337
