### ISSUE TITLE
Create examples folder and make it part of PR process

### ISSUE THREAD

**Issue by kbudde** [mykso/myks#51]
Other projects like [client-go](https://github.com/kubernetes/client-go) are providing an [examples](https://github.com/kubernetes/client-go/tree/master/examples) folder inside their repositoy.
Examples are a good way to learn and help users understand how to use a product much faster than detailed documentation.

But for us, examples offer even more potential. With examples we can check that Myks generates the result we expect (end2end tests). 

The question is how to integrate it into the process:
a) If we force the rendering of the examples at PR creation from the user we will have many merge conflicts for paralel PRs. But we would see the change directly.
b) If we render only in the main branch, a pipeline commit is needed 

Proposal:
- A PR job which outputs the Diff for the examples
- Rendering in Main

**Comment by Zebradil** [comment]
**Context:**
> I planned to have a separate [repository for examples](https://github.com/mykso/myks-examples) because they'll contain a lot of directories and files. There we could share all kinds of applications. I don't have a strong opinion about that but still think that it's better to keep such examples in a separate repo.

But we do need e2e tests and basic examples in this repo.

I don't see an issue with the option a). In most cases, code changes won't affect rendered files, hence there won't be conflicts. In CI for PRs, we can check that e2e tests don't actually change any files. If they do, the job would be marked as failed.

P.S.: The separate repo with examples we can later repurpose to a sort of a library or just get rid of it.
