### ISSUE TITLE
[fix] Cleanup deleted envs and apps 

### ISSUE THREAD

**Issue by fritzduchardt** [mykso/myks#63]
Deleted environments and applications should be removed from envs file structure and rendered directory.

**Comment by Zebradil** [comment]
#89 implements removal from the `rendered/envs` and `rendered/argocd` directories, but not from `envs/**/_apps/*` directories.

Files in the `_app/*` directories can be created by users, we should not touch them. With that, cleaning up `.myks` directory there doesn't seem to bring a lot of value. If a user decides to cleanup, they have to do that manually.
