### ISSUE TITLE
[bug] Tests create myks' service files in the repo

### ISSUE THREAD

**Issue by Zebradil** [mykso/myks#91]
```shell
# Ensure this prints nothing in a clean working copy
git status --porcelain
# Now run tests
go test ./...
# See new files
git status --porcelain
# ?? internal/myks/.myks/
```

**Comment by kbudde** [comment]
@Zebradil as the files are ignored, I would close this issue, ok?

**Comment by Zebradil** [comment]
I'm not sure. Yes, they aren't getting into git, but it still feels messy. Or is it a normal practice for tests to leave stuff behind? Let's close it. I'll reopen if it'll be bugging me :-)
